services:
  - type: web
    name: dmyf
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEV_MODE
        value: production
      - key: REACT_APP_BASEURL
        value: /api/v1
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_NAME
        value: DMYF
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLIENT_URL
        sync: false
