export const normalizeCityKey = (value = "") =>
  String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z]/g, "");

// Provided list (deduped at runtime).
const PAKISTAN_CITIES = [
  "Karachi",
  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Mirpur Khas",
  "Nawabshah",
  "Jacobabad",
  "Shikarpur",
  "Khairpur",
  "Dadu",
  "Badin",
  "Thatta",
  "Ghotki",
  "Kandhkot",
  "Kashmore",
  "Umerkot",
  "Mithi",
  "Tando Allahyar",
  "Tando Adam",
  "Tando Muhammad Khan",
  "Kotri",
  "Sehwan",
  "Matiari",
  "Halla",
  "Bhit Shah",
  "Shahdadpur",
  "Sanghar",
  "Sinjhoro",
  "Digri",
  "Kunri",
  "Samaro",
  "Jhudo",
  "Diplo",
  "Nagarparkar",
  "Islamkot",
  "Pangrio",
  "Talhar",
  "Matli",
  "Golarchi",
  "Sujawal",
  "Jati",
  "Mirpur Bathoro",
  "Gharo",
  "Keti Bandar",
  "Mirpur Sakro",
  "Gambat",
  "Sobhodero",
  "Kingri",
  "Kot Digri",
  "Ranipur",
  "Thari Mirwah",
  "Pano Aqil",
  "Rohari",
  "Ubauro",
  "Daharki",
  "Mirpur Mathelo",
  "Thul",
  "Warah",
  "Dokri",
  "Ratodero",
  "Badah",
  "Mehar",
  "Khairpur Nathan Shah",
  "Johi",
  "Bhan",
  "Lakhi",
  "Madeji",
  "Garhiyasin",
  "Kumb",
  "Chak",
  "Kandiaro",
  "Mehrabpur",
  "Naushahro Feroze",
  "Moro",
  "Bandhi",
  "Sakrand",
  "Daur",
  "Qazi Ahmed",
  "Jam Sahib",
  "Tando Jam",

  "Lahore",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Bahawalpur",
  "Sargodha",
  "Sheikhupura",
  "Rahim Yar Khan",
  "Gujrat",
  "Jhelum",
  "Kasur",
  "Okara",
  "Sahiwal",
  "Pakpattan",
  "Chiniot",
  "Toba Tek Singh",
  "Jhang",
  "Mianwali",
  "Bhakkar",
  "Khushab",
  "Attock",
  "Chakwal",
  "Narowal",
  "Hafizabad",
  "Mandi Bahauddin",
  "Vehari",
  "Lodhran",
  "Khanewal",
  "Muzaffargarh",
  "Rajanpur",
  "Layyah",
  "Bahawalnagar",
  "Ahmedpur East",
  "Hassan Abdal",
  "Kamoke",
  "Wazirabad",
  "Daska",
  "Sambrial",
  "Pasrur",
  "Kharian",
  "Lalamusa",
  "Jalalpur Jattan",
  "Sarai Alamgir",
  "Bhalwal",
  "Kot Mumin",
  "Sillanwali",
  "Shorkot",
  "Ahmadpur Sial",
  "Gojra",
  "Kamalia",
  "Pirmahal",
  "Arifwala",
  "Chichawatni",
  "Burewala",
  "Mailsi",
  "Dunyapur",
  "Kabirwala",
  "Kahror Pakka",
  "Jalalpur Pirwala",
  "Alipur",
  "Kot Addu",
  "Taunsa",
  "Jampur",
  "Muridke",
  "Sharaqpur",
  "Ferozewala",
  "Pattoki",
  "Phool Nagar",
  "Renala Khurd",
  "Depalpur",
  "Haveli Lakha",
  "Hujra Shah Muqeem",
  "Fort Abbas",
  "Haroonabad",
  "Chishtian",
  "Yazman",
  "Khairpur Tamewali",
  "Liaquatpur",
  "Khanpur",
  "Sadiqabad",
  "Rahimabad",
  "Kot Samaba",
  "Zafarwal",
  "Shakargarh",
  "Narang",
  "Sangla Hill",
  "Safdarabad",
  "Warburton",
  "Farooqabad",
  "Raiwind",
  "Kot Radha Kishan",
  "Chunian",
  "Bhai Pheru",
  "Baddomalhi",
  "Eminabad",
  "Qila Didar Singh",
  "Nowshera Virkan",
  "Alipur Chattha",
  "Rasulnagar",
  "Dinga",
  "Jalalpur Sharif",
  "Pind Dadan Khan",
  "Khewra",
  "Choa Saidan Shah",
  "Dhudial",
  "Talagang",
  "Fateh Jang",
  "Hazro",
  "Pindigheb",
  "Isa Khel",
  "Kalabagh",
  "Daud Khel",
  "Kundian",
  "Darya Khan",
  "Mankera",
  "Kotla Arab Ali Khan",
  "Malakwal",
  "Phalia",
  "Jalalpur Bhattian",
  "Sultanpur Lodhi",
  "Shujaabad",
  "Qadirpur Ran",
  "Khanqah Sharif",
  "Ahmad Nagar",
  "Pir Mahal",
  "Noorpur Thal",
  "Jauharabad",
  "Quatabad",
  "Khairpur Sadat",
  "Kot Mithan",
  "Rojan",
  "Fazilpur",
  "Chowk Azam",
  "Karor Lal Esan",
  "Fatehpur",
  "Kot Sultan",
  "Ahmadpur Lama",
  "Bhong",
  "Zahir Pir",
  "Khan Bela",
  "Kot Chatta",
  "Tranda Sawai Khan",
  "Ahmadpur Lamma",
  "Dunyapur",
  "Samundri",
  "Tandlianwala",
  "Chak Jhumra",
  "Jaranwala",
  "Khurrianwala",
  "Satiana",
  "Mamun Kanjan",
  "Buchiana",
  "Ghojra",
  "Shahkot",
  "Habibabad",
  "Chak 46 GB",
  "Chak 208 RB",
  "Chunian",
  "Shahpur",
  "Shahpur Saddar",
  "Bhagtanwala",
  "Sodhra",
  "Qadirabad",
  "Shadiwal",
  "Lilla",
  "Dhoke Hassu",
  "Kallar Kahar",
  "Choa Saidan Shah",
  "Bhera",
  "Bhawana",
  "Kot Naina",
  "Kot Sarwar",
  "Mehmood Kot",
  "Shadan Lund",
  "Kot Chutta",
  "Dajal",
  "Kot Mithan Sharif",
  "Rojan Sharif",

  "Quetta",
  "Turbat",
  "Khuzdar",
  "Gwadar",
  "Chaman",
  "Zhob",
  "Sibi",
  "Loralai",
  "Pishin",
  "Mastung",
  "Kalat",
  "Hub",
  "Dera Murad Jamali",
  "Nushki",
  "Dalbandin",
  "Chagai",
  "Kharan",
  "Washuk",
  "Panjgur",
  "Pasni",
  "Ormara",
  "Gaddani",
  "Bela",
  "Uthal",
  "Winder",
  "Harnai",
  "Mach",
  "Kolpur",
  "Gandawa",
  "Jhalk Magsi",
  "Surab",
  "Qila Abdullah",
  "Qila Saifullah",
  "Musakhel",
  "Barkhan",
  "Kohlu",
  "Dera Bugti",
  "Sui",
  "Kahan",
  "Bostan",
  "Kan Mehtarzai",
  "Dukki",
  "Lehri",
  "Talli",
  "Zehri",
  "Naal",
  "Buleda",
  "Tump",
  "Mand",
  "Paroom",
  "Pir Koh",
  "Sanjavi",
  "Nokundi",
  "Taftan",
  "Rakhni",
  "Balochabad",

  "Peshawar",
  "Mardan",
  "Abbottabad",
  "Mingora",
  "Kohat",
  "Dera Ismail Khan",
  "Bannu",
  "Swabi",
  "Nowshera",
  "Charsadda",
  "Mansehra",
  "Haripur",
  "Batkhela",
  "Timergara",
  "Chitral",
  "Tank",
  "Hangu",
  "Karak",
  "Lakki Marwat",
  "Shabqadar",
  "Tangi",
  "Takht Bhai",
  "Katlang",
  "Rustam",
  "Topi",
  "Lahor",
  "Zaida",
  "Mathra",
  "Bara",
  "Jamrud",
  "Landi Kotal",
  "Parachinar",
  "Sadda",
  "Thall",
  "Doaba",
  "Khar",
  "Nawagai",
  "Mamond",
  "Barikot",
  "Kabal",
  "Matta",
  "Khwazakhela",
  "Bahrain",
  "Kalam",
  "Alpuri",
  "Besham",
  "Pattan",
  "Dasu",
  "Kolai",
  "Dir",
  "Drosh",
  "Booni",
  "Mastuj",
  "Ayun",
  "Garhi Habibullah",
  "Balakot",
  "Baffa",
  "Batgram",
  "Thakot",
  "Chakdara",
  "Samarbagh",
  "Timergara",
  "Shahi Bagh",
  "Pabbi",
  "Akora Khattak",
  "Jehangira",
  "Risalpur",
  "Cherat",
  "Utmanzai",
  "Rajjar",
  "Prang",
  "Shakardarra",
  "Lachi",
  "Ghazi",
  "Khalabat",
  "Tarbela",
  "Havelian",
  "Khaki",
  "Shinkiari",
  "Darband",
  "Shinkiari",
  "Domel",
  "Kulachi",
  "Paharpur",
  "Daraban",
  "Paroa",
  "Serai Gambila",
  "Tajori",
  "Ghazni Khel",
];

const dedupe = (arr) => {
  const seen = new Set();
  const result = [];
  for (const item of arr) {
    const key = normalizeCityKey(item);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(item);
  }
  return result;
};

export const CANONICAL_CITIES = dedupe(PAKISTAN_CITIES);

export const getCitySuggestions = (input = "", limit = 8) => {
  const raw = String(input || "").trim();
  const key = normalizeCityKey(raw);
  if (!key) return [];

  const suggestions = [];

  for (const city of CANONICAL_CITIES) {
    const cityKey = normalizeCityKey(city);
    if (!cityKey.startsWith(key)) continue;
    if (!suggestions.includes(city)) suggestions.push(city);
    if (suggestions.length >= limit) break;
  }

  return suggestions.slice(0, limit);
};
